### ISSUE TITLE
HTML5 o XHTML? 

### ISSUE THREAD

**Issue by AkaiSara** [RiccardoAgatea/Progetto-TecWeb#32]
Nella pagina `nuovaserie.html` viene usato più volte `type="number"` e gli attributi `min` e `max`. Consiglio di valutare se scrivere questa pagina in xhtml o in html5

**Comment by AkaiSara** [comment]
Stessa cosa è presente nella pagina `nuovofilm.html`

**Comment by RiccardoAgatea** [comment]
Pensavo avessimo già deciso di scrivere quelle pagine in HTML5

**Comment by AkaiSara** [comment]
Allora bisogna cambiare il `DOCTYPE` a inizio di entrambe le pagine

**Comment by RiccardoAgatea** [comment]
Bisogna anche cambiare l'icona della validità del W3C. Al momento è quella di XHTML 1.0 in tutte le pagine.

**Comment by AkaiSara** [comment]
Consiglio di aprire un'altra issue, relativa alle icone della validità
